# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mission1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Mission1Ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(751, 751)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 751, 751))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0.492174, y1:0.018, x2:0.502, y2:1, stop:0.432836 rgba(255, 53, 56, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.widget.setObjectName("widget")
        self.image_label = QtWidgets.QLabel(self.widget)
        self.image_label.setGeometry(QtCore.QRect(0, 0, 751, 751))
        self.image_label.setObjectName("image_label")
        self.answer_button = QtWidgets.QPushButton(self.widget)
        self.answer_button.setGeometry(QtCore.QRect(280, 620, 201, 111))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(9)
        self.answer_button.setFont(font)
        self.answer_button.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(201, 255, 255);\n"
"font: 75 8pt \"MS Serif\";")
        self.answer_button.setObjectName("answer_button")
        self.answer_label = QtWidgets.QLabel(self.widget)
        self.answer_label.setGeometry(QtCore.QRect(240, 460, 291, 51))
        self.answer_label.setStyleSheet("font: 57 14pt \"Dubai Medium\";\n"
"color: rgb(85, 0, 255);")
        self.answer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.answer_label.setObjectName("answer_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.image_label.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.answer_button.setText(_translate("Dialog", "LOCATİON"))
        self.answer_label.setText(_translate("Dialog", "-------------------------------------------------"))
