# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ekran2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

class Ekran2(QWidget):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(440, 620)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 440, 620))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0.492174, y1:0.018, x2:0.502, y2:1, stop:0.432836 rgba(255, 53, 56, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.widget.setObjectName("widget")
        self.who_label = QtWidgets.QLabel(self.widget)
        self.who_label.setGeometry(QtCore.QRect(0, 80, 441, 111))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.who_label.setFont(font)
        self.who_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.who_label.setTextFormat(QtCore.Qt.AutoText)
        self.who_label.setAlignment(QtCore.Qt.AlignCenter)
        self.who_label.setObjectName("who_label")
        self.mission_button = QtWidgets.QPushButton(self.widget)
        self.mission_button.setGeometry(QtCore.QRect(120, 240, 201, 61))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(9)
        self.mission_button.setFont(font)
        self.mission_button.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(201, 255, 255);\n"
"font: 75 8pt \"MS Serif\";")
        self.mission_button.setObjectName("mission_button")
        self.mission2_button = QtWidgets.QPushButton(self.widget)
        self.mission2_button.setGeometry(QtCore.QRect(120, 350, 201, 61))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(9)
        self.mission2_button.setFont(font)
        self.mission2_button.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(201, 255, 255);\n"
"font: 75 8pt \"MS Serif\";")
        self.mission2_button.setObjectName("mission2_button")
        self.mission3_button = QtWidgets.QPushButton(self.widget)
        self.mission3_button.setGeometry(QtCore.QRect(120, 460, 201, 61))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(9)
        self.mission3_button.setFont(font)
        self.mission3_button.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(201, 255, 255);\n"
"font: 75 8pt \"MS Serif\";")
        self.mission3_button.setObjectName("mission3_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.who_label.setText(_translate("Dialog", "welcome"))
        self.mission_button.setText(_translate("Dialog", "Görev1"))
        self.mission2_button.setText(_translate("Dialog", "Görev2"))
        self.mission3_button.setText(_translate("Dialog", "Görev3"))
