# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ekran1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

class Ekran1(QWidget):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(435, 620)
        Dialog.setStyleSheet("")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 40, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 440, 620))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0.492174, y1:0.018, x2:0.502, y2:1, stop:0.432836 rgba(255, 53, 56, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.widget.setObjectName("widget")
        self.welcome_label = QtWidgets.QLabel(self.widget)
        self.welcome_label.setGeometry(QtCore.QRect(-20, 110, 461, 111))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.welcome_label.setFont(font)
        self.welcome_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.welcome_label.setTextFormat(QtCore.Qt.AutoText)
        self.welcome_label.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_label.setObjectName("welcome_label")
        self.signup_button = QtWidgets.QPushButton(self.widget)
        self.signup_button.setGeometry(QtCore.QRect(130, 450, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(9)
        self.signup_button.setFont(font)
        self.signup_button.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(201, 255, 255);\n"
"font: 75 8pt \"MS Serif\";")
        self.signup_button.setObjectName("signup_button")
        self.id_field = QtWidgets.QLineEdit(self.widget)
        self.id_field.setGeometry(QtCore.QRect(70, 240, 311, 51))
        self.id_field.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.id_field.setObjectName("id_field")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(75, 220, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(75, 310, 81, 16))
        self.label_2.setObjectName("label_2")
        self.error_label = QtWidgets.QLabel(self.widget)
        self.error_label.setGeometry(QtCore.QRect(70, 410, 311, 21))
        self.error_label.setStyleSheet("\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(209, 0, 0);")
        self.error_label.setObjectName("error_label")
        self.password_field = QtWidgets.QLineEdit(self.widget)
        self.password_field.setGeometry(QtCore.QRect(70, 331, 311, 51))
        self.password_field.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.password_field.setObjectName("password_field")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.welcome_label.setText(_translate("Dialog", "WELCOME"))
        self.signup_button.setText(_translate("Dialog", "Sign in"))
        self.label.setText(_translate("Dialog", "Id"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.error_label.setText(_translate("Dialog", "-"))
