# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_checkbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(410, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(140, 310, 121, 28))
        self.button.setObjectName("button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 370, 341, 81))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 50, 141, 231))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 111, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cinema_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cinema_cb.setObjectName("cinema_cb")
        self.verticalLayout.addWidget(self.cinema_cb)
        self.book_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.book_cb.setObjectName("book_cb")
        self.verticalLayout.addWidget(self.book_cb)
        self.spor_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.spor_cb.setObjectName("spor_cb")
        self.verticalLayout.addWidget(self.spor_cb)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(230, 50, 141, 231))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 111, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cinema_cb_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cinema_cb_2.setObjectName("cinema_cb_2")
        self.verticalLayout_2.addWidget(self.cinema_cb_2)
        self.book_cb_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.book_cb_2.setObjectName("book_cb_2")
        self.verticalLayout_2.addWidget(self.book_cb_2)
        self.spor_cb_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.spor_cb_2.setObjectName("spor_cb_2")
        self.verticalLayout_2.addWidget(self.spor_cb_2)
        self.label.raise_()
        self.button.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 410, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button.setText(_translate("MainWindow", "Take the chosed"))
        self.label.setText(_translate("MainWindow", "-"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.cinema_cb.setText(_translate("MainWindow", "Cinema"))
        self.book_cb.setText(_translate("MainWindow", ".Reading book"))
        self.spor_cb.setText(_translate("MainWindow", "Spor"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.cinema_cb_2.setText(_translate("MainWindow", "Cinema"))
        self.book_cb_2.setText(_translate("MainWindow", ".Reading book"))
        self.spor_cb_2.setText(_translate("MainWindow", "Spor"))
