# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_comboboxform.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(383, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.city_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.city_comboBox.setGeometry(QtCore.QRect(70, 30, 231, 41))
        self.city_comboBox.setObjectName("city_comboBox")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(50, 410, 281, 61))
        self.result_label.setObjectName("result_label")
        self.getItem_Button = QtWidgets.QPushButton(self.centralwidget)
        self.getItem_Button.setGeometry(QtCore.QRect(70, 320, 100,61))
        self.getItem_Button.setObjectName("getItem_Button")
        self.load_Button = QtWidgets.QPushButton(self.centralwidget)
        self.load_Button.setGeometry(QtCore.QRect(200, 320, 100, 61))
        self.load_Button.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 383, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.result_label.setText(_translate("MainWindow", "------------------------------------------------------"))
        self.getItem_Button.setText(_translate("MainWindow", "Get item"))
        self.load_Button.setText(_translate("MainWindow", "Load item"))
