# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_listform.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(368, 637)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(40, 10, 291, 271))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 290, 221, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.add_pushButton.setObjectName("add_pushButton")
        self.verticalLayout.addWidget(self.add_pushButton)
        self.cut_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cut_pushButton.setObjectName("cut_pushButton")
        self.verticalLayout.addWidget(self.cut_pushButton)
        self.remove_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.remove_pushButton.setObjectName("remove_pushButton")
        self.verticalLayout.addWidget(self.remove_pushButton)
        self.up_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.up_pushButton.setObjectName("up_pushButton")
        self.verticalLayout.addWidget(self.up_pushButton)
        self.down_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.down_pushButton.setObjectName("down_pushButton")
        self.verticalLayout.addWidget(self.down_pushButton)
        self.sort_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sort_pushButton.setObjectName("sort_pushButton")
        self.verticalLayout.addWidget(self.sort_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.exit_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.verticalLayout.addWidget(self.exit_pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 368, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_pushButton.setText(_translate("MainWindow", "Add"))
        self.cut_pushButton.setText(_translate("MainWindow", "Cut"))
        self.remove_pushButton.setText(_translate("MainWindow", "Remove"))
        self.up_pushButton.setText(_translate("MainWindow", "Up"))
        self.down_pushButton.setText(_translate("MainWindow", "Down"))
        self.sort_pushButton.setText(_translate("MainWindow", "Sort"))
        self.exit_pushButton.setText(_translate("MainWindow", "Exit"))
