# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_radiobuttonform.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(367, 591)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.country_lbl = QtWidgets.QLabel(self.centralwidget)
        self.country_lbl.setGeometry(QtCore.QRect(40, 400, 291, 31))
        self.country_lbl.setObjectName("country_lbl")
        self.country_Button = QtWidgets.QPushButton(self.centralwidget)
        self.country_Button.setGeometry(QtCore.QRect(40, 460, 93, 28))
        self.country_Button.setObjectName("country_Button")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 460, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 309, 191))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 30, 311, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tr_radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.tr_radioButton.setObjectName("tr_radioButton")
        self.gridLayout.addWidget(self.tr_radioButton, 2, 0, 1, 1)
        self.azari_radioButton_4 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.azari_radioButton_4.setObjectName("azari_radioButton_4")
        self.gridLayout.addWidget(self.azari_radioButton_4, 3, 0, 1, 1)
        self.greek_radioButton_3 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.greek_radioButton_3.setObjectName("greek_radioButton_3")
        self.gridLayout.addWidget(self.greek_radioButton_3, 0, 0, 1, 1)
        self.grmn_radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.grmn_radioButton_2.setObjectName("grmn_radioButton_2")
        self.gridLayout.addWidget(self.grmn_radioButton_2, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 210, 309, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 331, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lise_radioButton_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.lise_radioButton_5.setObjectName("lise_radioButton_5")
        self.verticalLayout.addWidget(self.lise_radioButton_5)
        self.lisans_radioButton_6 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.lisans_radioButton_6.setObjectName("lisans_radioButton_6")
        self.verticalLayout.addWidget(self.lisans_radioButton_6)
        self.yksklisans_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.yksklisans_radioButton.setObjectName("yksklisans_radioButton")
        self.verticalLayout.addWidget(self.yksklisans_radioButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 367, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.country_lbl.setText(_translate("MainWindow", "-"))
        self.country_Button.setText(_translate("MainWindow", "Country"))
        self.pushButton_2.setText(_translate("MainWindow", "Education"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.tr_radioButton.setText(_translate("MainWindow", "Türkiye"))
        self.azari_radioButton_4.setText(_translate("MainWindow", "azarbaycan"))
        self.greek_radioButton_3.setText(_translate("MainWindow", "Yunanistan"))
        self.grmn_radioButton_2.setText(_translate("MainWindow", "Almanya"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.lise_radioButton_5.setText(_translate("MainWindow", "Lise"))
        self.lisans_radioButton_6.setText(_translate("MainWindow", "Lisans"))
        self.yksklisans_radioButton.setText(_translate("MainWindow", "Yükseklisans"))
